language: c
compiler: gcc
install:
- sudo apt-get install valgrind
after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
script: make doTest
notifications:
  email: false
  on_failure: always
  on_success: always
env:
  global:
    secure: kQ3WZibP+h5csRtbsElVPxWWqx60L/CVBnzxCN6D6rHfogJaWQT5L146SKfqRXUy69I83bPaH5saDOws1VZ+Wh+jGV/aTnE2ZCGLkkh2Et4EUjTeqagDUgDdsxVtAZNyc9u59FM8v7gDIL1E2xrGqiHtA2cbvUsRnj07Mki/y0mKAAm1geCstj6ErusW4ub72yF7tYGeSg0UZynOTZiiww+PPnb5XgsN0BIhWgtMQmoRq8V9hGLZ1txD4HuxsootTkYwYsr1qRK5uKl9oujk7y/rgkRok6IwBh0pUs79kvklvea6BLCBPzR1md2htKsyfcIsxspPzZf7khmpZcHfnv3LA3p3hZgw8KamJj1Zy45lZC5J65S0pU8C8gX4KFB+wUyZH36O6mf2lls1M/a0KTtcZrjsJiPTrd76ypb6NSl3rTXN85k+ije3TRwQrRlo8j5zZtetkGY6fIsN37C/Ae6hkRSZrpUvnhoZhvw6N34Rk3b+83LoP1saDV89mclvV2crV/LGXpLZ5jV/f+dRLiDuqNCY2/mjpDAkktq9CvXNI03mZa1mK5wGuLHAJIGANTQ4Nl3jXjI2kGUPy3Mu3qHy2CPlkq03r4fMafz/7rPOOFqFkCnPoXbA2LpCe2z29yh0Z+KqH414QnY5B6YLgHkMAYtQOuUlzibaPLUAXOs=
