language: c
compiler: gcc
install:
  - sudo apt-get install valgrind
script: make doTest
notifications:
  email: false
  on_failure: always
  on_success: always
  webhooks: https://travis-webhook-discord.herokuapp.com/webhook
